language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
cache: pip
install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install coveralls
env:
  global:
    # Bucket managed by cloud.gov at eregs-nc/integration
    # Note: Persistent credentials set manually to prevent reset on app unbind
    - BUCKET=cg-bcf4ec52-851a-4aaf-b353-acc25474a336
    - secure: "Hkxewgry7TIDnAWclU9mxYGZqivzPbO085PJg1gMblvsTeYSxPjtX7amzpS6yFA24S+oN/zG0Hg7ya+4TVfl8BCbuWPymKYXA07uthExUQ+gPwdz476ZygUpuUdtpeVveMFE8StGTJ/pdE4o1sYBuejkEi7K3y5yyOCf8/POn8A="
    - secure: "fy3VSSwfHdeEs9O4nri/JCV0c7UH5HwKCFCj5bJnSWyBFwHS5gbicncC3DoqBJArrIza+HPmUbeYzhiP5i0di9kc5Ss4Fnq3NgnB8UJXOr8Jwpdl4c1CzBklvv1lxNgqKrNcqsmdtfZWM+ib942tXxb9BbABePWYTPe4cMPpbok="
  matrix:
    - INTEGRATION_TARGET=
    - INTEGRATION_TARGET=fec
    - INTEGRATION_TARGET=atf
script:
  - ./test-travis.sh
after_success:
  - if [[ $INTEGRATION_TARGET = '' ]] && [[ $TRAVIS_PYTHON_VERSION = '2.7' ]]; then coveralls; fi
